name: rgb_trim
description: Control leds via BLE.
publish_to: "none"

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  # change_app_package_name: ^0.1.3
  # flutter_launcher_icons: "^0.9.2"
  # flutter_native_splash: ^2.1.6
  flutter_test:
    sdk: flutter
  flutter_blue: ^0.8.0

flutter:
  uses-material-design: true

# flutter_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "images/logo_bg.png"

# flutter_native_splash:
#   background_image: "images/splash.png"

  # To add assets to your application, add an assets section, like this:
  assets:
  - images/logo.png
  - images/logo_bg.png
  - images/splash.png